### ISSUE TITLE
[49] General correction on the game's numerical system

### ISSUE THREAD

**Issue by duduGrassUoft** [CSC207-2023Y-UofT/course-project-monopoly#49]
This is an upgrade that increases the top level of properties from 3 to 5, and initial money from 1000 to 1500. The new numerical system better imitates the classic Monoply board game, which should ensure that the game will eventually end with a single winner not going bankrupt.

**Comment by duduGrassUoft** [comment]
PropertyGenerator and the data csv file will be changed. If there're other files that should be modified to prevent bugs, leave a comment plz

**Comment by AlwynYin** [comment]
I think we should support 3/5 levels concurrently because 3-level game is easier to test, and we can use separate csv files for testing and playing

**Comment by duduGrassUoft** [comment]
> I think we should support 3/5 levels concurrently because 3-level game is easier to test, and we can use separate csv files for testing and playing

Understood. I will create a separate RevisedPropertyGenerator and revised_properties.csv. The current PropertyGenerator and properties_example.csv will be left slightly changed in detail but unchanged in functionality.

**Comment by duduGrassUoft** [comment]
Hmm, it will take more time to write the codes clean here. I will leave RevisedPropertyGenerator and PropertyGenerator very similar, since PropertyGenerator will be eventually deleted.
