### ISSUE TITLE
[Feature 6] Position Impactor

### ISSUE THREAD

**Issue by hecateli** [CSC207-2023Y-UofT/course-project-monopoly#8]
There are two functions:
1) relative movement: Moving forward or backward x blocks
2) absolute movement: Moving to a specific block

**Comment by AlwynYin** [comment]
![IMG_C1BCBC61785F-1](https://github.com/CSC207-2023Y-UofT/course-project-monopoly/assets/73570489/8af8fad0-828c-4525-99e7-d6a7bfbbc563)
Structure of PositionImpactor
